import '../zone.dart';

class Belgium extends Zone {
  Belgium() {
    surnames = [
      // List of surnames
      "Dupont",
      "Dubois",
      "Martens",
      "Jacobs",
      "Janssens",
      "Maes",
      "Lambert",
      "De Smet",
      "Mertens",
      "Claes",
      "Willems",
      "De Vos",
      "Vermeulen",
      "Wouters",
      "Van den Berg",
      "Desmet",
      "Van Damme",
      "Pauwels",
      "Peeters",
      "Vandenberghe",
      "Dumont",
      "Vandeweghe",
      "Stevens",
      "Vandenberg",
      "Vandamme",
      "Rousseau",
      "Smeets",
      "Peters",
      "Vandevelde",
      "Vandeput",
      "Noël",
      "Vanhove",
      "Vandenbossche",
      "Vanhoutte",
      "Verhaeghe",
      "Govaert",
      "Jans",
      "Verhoeven",
      "Vandecasteele",
      "Van Dyck",
      "Devos",
      "Vandewalle",
      "Van den Broeck",
      "Van den Bosch",
      "Lefebvre",
      "Dewitte",
      "Vancamp",
      "Vanderveken",
      "Devroe",
      "Vandenbergh",
      "Van Hout",
      "Van Rompaey",
      "Verhaegen",
      "Van den Broek",
      "Dumoulin",
      "Lemmens",
      "Van Dijk",
      "Luyten",
      "Vanderstraeten",
      "Vanhulle",
      "Van den Brande",
      "Vandenbroucke",
      "De Backer",
      "Vandevenne",
      "Vanderheyden",
      "Vancampen",
      "Van Belle",
      "Didden",
      "De Winter",
      "Van Bael",
      "Van Acker",
      "Vanhorenbeke",
      "Vermeiren",
      "Verheyen",
      "De Wilde",
      "De Meyer",
      "Van Bogaert",
      "Lauwers",
      "Vandebroek",
      "Bogaert",
      "Peeters",
      "Vanhout",
      "Vandermeulen",
      "Vandevelde",
      "Van Herck",
      "Verstraete",
      "Van den Abeele",
      "Vansant",
      "Mertens",
      "Vandenberg",
      "Van de Velde",
      "Van Damme"
    ];

    namesM = [
      // List of male names
      "Lucas",
      "Liam",
      "Noah",
      "Adam",
      "Ethan",
      "Matteo",
      "Louis",
      "Victor",
      "Jules",
      "Maxime",
      "Thomas",
      "Arthur",
      "Finn",
      "Hugo",
      "Olivier",
      "Leo",
      "Simon",
      "Gabriel",
      "Nathan",
      "Alexander",
      "Samuel",
      "David",
      "Mathis",
      "Benjamin",
      "Elias",
      "Théo",
      "Raphael",
      "Aaron",
      "Antoine",
      "Julien",
      "Benoit",
      "Paul",
      "Matthias",
      "Pierre",
      "Vincent",
      "Cédric",
      "Nicolas",
      "Tristan",
      "Emile",
      "Jonathan",
      "Xavier",
      "Quentin",
      "Evan",
      "Florent",
      "Gilles",
      "Arnaud",
      "Laurent",
      "Christophe",
      "Maurice",
      "Yves",
      "Georges",
      "Oscar",
      "Claude",
      "René",
      "André",
      "Bernard",
      "François",
      "Gustave",
      "Henri",
      "Jacques",
      "Joseph",
      "Louis",
      "Marcel",
      "Roger",
      "Thierry",
      "Willem",
      "Lucien",
      "Émile",
      "Felix",
      "Oscar",
      "Edgar",
      "Camil",
      "Cyril",
      "Romain",
      "Sébastien",
      "Clement",
      "Jérôme",
      "Guillaume",
      "Léon",
      "Nico",
      "Mathieu",
      "Francois",
      "Philippe",
      "Armand",
      "Thibaut",
      "Bertrand",
      "Constant",
      "Rémi",
      "Augustin",
      "Julius",
      "Adrien",
      "Luc",
      "Hector",
      "Martin",
      "Bruno",
      "Franck",
      "Edmond",
      "Gaston"
    ];

    namesW = [
      // List of female names
      "Emma",
      "Louise",
      "Olivia",
      "Mila",
      "Alice",
      "Juliette",
      "Léa",
      "Camille",
      "Lina",
      "Zoé",
      "Elena",
      "Anna",
      "Lucie",
      "Elise",
      "Sarah",
      "Nora",
      "Ella",
      "Lara",
      "Sophie",
      "Charlotte",
      "Amélie",
      "Léonie",
      "Clara",
      "Manon",
      "Fleur",
      "Lola",
      "Noémie",
      "Hannah",
      "Inès",
      "Célia",
      "Victoria",
      "Eva",
      "Marie",
      "Lou",
      "Chloé",
      "Elsa",
      "Adèle",
      "Rose",
      "Axelle",
      "Maëlle",
      "Jade",
      "Léonore",
      "Laure",
      "Aline",
      "Céline",
      "Pauline",
      "Louisa",
      "Lise",
      "Rosalie",
      "Yasmine",
      "Aurélie",
      "Daphné",
      "Nina",
      "Elodie",
      "Gaëlle",
      "Eloïse",
      "Luna",
      "Ambre",
      "Zara",
      "Mia",
      "Émilie",
      "Livia",
      "Anouk",
      "Maud",
      "Alicia",
      "Lynn",
      "Élise",
      "Julia",
      "Margaux",
      "Zélie",
      "Mélanie",
      "Violette",
      "Mya",
      "Lara",
      "Alizée",
      "Tess",
      "Axelle",
      "Selma",
      "Sara",
      "Elif",
      "Inaya",
      "Lola",
      "Lise",
      "Sofia",
      "Mara",
      "Amy",
      "Jenna",
      "Cleo",
      "Romy",
      "Zara",
      "Mona",
      "Lyana",
      "Mila",
      "Noor",
      "Nora"
    ];
  }
}
