import '../zone.dart';

/// Zone China
class China extends Zone {
  @override
  String id = "china";
  China() {
    surnames = [
      // List of surnames
      "Li",
      "Wang",
      "Zhang",
      "Liu",
      "Chen",
      "Yang",
      "Huang",
      "Zhao",
      "Zhou",
      "Wu",
      "Xu",
      "Sun",
      "Ma",
      "Zhu",
      "Hu",
      "Guo",
      "He",
      "Gao",
      "Lin",
      "Lu",
      "Wei",
      "Jiang",
      "Fang",
      "Xie",
      "Shi",
      "Song",
      "Yu",
      "Pan",
      "Yuan",
      "Cao",
      "Tang",
      "Qian",
      "Deng",
      "Yao",
      "Su",
      "Wu",
      "Zou",
      "Xiong",
      "Xiao",
      "Tian",
      "Cheng",
      "Duan",
      "Feng",
      "Yin",
      "Hao",
      "Chang",
      "Yan",
      "Ren",
      "Liang",
      "Liang",
      "Shen",
      "Xia",
      "Gong",
      "Yi",
      "Cai",
      "Wang",
      "Tang",
      "Xu",
      "Xu",
      "Wang",
      "Liu",
      "Yin",
      "Yang",
      "Yuan",
      "Xie",
      "Li",
      "Chen",
      "Zhang",
      "Zhou",
      "Wu",
      "Sun",
      "Ma",
      "Hu",
      "Gao",
      "He",
      "Zhao",
      "Fang",
      "Jiang",
      "Zhu",
      "Wei",
      "Guo",
      "Lu",
      "Song",
      "Pan",
      "Shi",
      "Yuan",
      "Yu",
      "Cao",
      "Tang",
      "Deng",
      "Xiao",
      "Ren",
      "Yao",
      "Liang",
      "Cheng"
    ];

    namesM = [
      // List of male names
      "Zhang Wei",
      "Li Jie",
      "Wang Lei",
      "Chen Hao",
      "Liu Ming",
      "Yang Tao",
      "Xu Yu",
      "Huang Peng",
      "Zhao Xin",
      "Wu Fei",
      "Zhu Ning",
      "Qian Long",
      "Sun Kai",
      "Ma Shuai",
      "Hu Chen",
      "Gao Wei",
      "Lin Jun",
      "He Wei",
      "Deng Li",
      "Cao Xiang",
      "Jiang Feng",
      "Yu Bo",
      "Xie Yun",
      "Tang Zhi",
      "Ren Qi",
      "Song Rui",
      "Pan Wen",
      "Zhou Yi",
      "Xiao Chen",
      "Lu Ming",
      "Fang Xin",
      "Jin Jing",
      "Wei Xuan",
      "Cheng Lin",
      "Shen Guo",
      "Yuan Tao",
      "Dai Wei",
      "Hao Lu",
      "Liao Xin",
      "Xiong Ji",
      "Kong Yue",
      "Tian Mei",
      "Zeng Sheng",
      "Fu Hai",
      "Zou Yang",
      "Wei Ran",
      "Chang Peng",
      "Chu Yu",
      "Tang Long",
      "Wang Kang",
      "Xiao Qiang",
      "Li Hong",
      "Yang Wei",
      "Zhang Yu",
      "Wu Xin",
      "Liu Qing",
      "Jiang Wen",
      "Chen Xing",
      "Huang Zhao",
      "Xu Ming",
      "Gao Jun",
      "Zhu Hao",
      "Qian Yue",
      "Sun Zhen",
      "Ma Dong",
      "Hu Fang",
      "Zhao Cheng",
      "Wang Ning",
      "Liu Qi",
      "Yang Xi",
      "Xu Yi",
      "Zhang Peng",
      "Li Xian",
      "Wang Chao",
      "Chen Chen",
      "Liu Xing",
      "Yu Zhu",
      "Huang Qiu",
      "Zheng Wei",
      "Wu Bo",
      "Jiang Kai",
      "Tang Lin",
      "Xiao Shen",
      "Lu Zhong",
      "Song Yi",
      "Hu Jian",
      "Gao Han",
      "Chen Bai",
      "Zhang Hao",
      "Li Yan",
      "Wang Yue",
      "Liu Ran",
      "Zhao Ao",
      "Xu Sen",
      "Sun Tian",
      "Ma Lian",
      "Huang Fan",
      "Cheng Jing",
      "Wu Xiang",
      "Zhang Yi",
      "Li Wu"
    ];

    namesW = [
      // List of female names
      "Mei Ling",
      "Xiu Yan",
      "Li Wei",
      "Yan Xin",
      "Jing Yi",
      "Hui Min",
      "Qing Xia",
      "Yu Xuan",
      "Fang Wei",
      "Xiao Hui",
      "Ling Wei",
      "Jia Li",
      "Yun Fei",
      "Xia Chen",
      "Wei Ning",
      "Zhu Li",
      "Jing Wen",
      "Rui Fang",
      "Xin Yue",
      "Li Na",
      "Zhi Yan",
      "Yan Jun",
      "Xiao Mei",
      "Qing Ling",
      "Jing Wei",
      "Hui Ling",
      "Yu Jie",
      "Fang Ting",
      "Xin Yi",
      "Mei Hua",
      "Xiu Ying",
      "Li Xia",
      "Yan Xi",
      "Jing Qian",
      "Hui Yan",
      "Qing Yun",
      "Yu Wen",
      "Fang Hui",
      "Xiao Fang",
      "Li Jing",
      "Zhi Hui",
      "Yan Ning",
      "Xiao Xuan",
      "Qing Wei",
      "Jing Xin",
      "Hui Zhen",
      "Yu Fang",
      "Fang Wei",
      "Xin Xin",
      "Mei Yan",
      "Xiu Fang",
      "Li Min",
      "Yan Mei",
      "Jing Zhu",
      "Hui Ning",
      "Qing Mei",
      "Yu Yan",
      "Fang Xin",
      "Xin Fang",
      "Mei Jie",
      "Xiu Mei",
      "Li Xuan",
      "Yan Zhu",
      "Jing Yue",
      "Hui Qian",
      "Qing Yan",
      "Yu Ting",
      "Fang Qing",
      "Xin Jing",
      "Mei Fang",
      "Xiu Jing",
      "Li Qing",
      "Yan Jie",
      "Jing Hui",
      "Hui Yu",
      "Qing Chen",
      "Yu Fang",
      "Fang Jia",
      "Xin Yu",
      "Mei Chen",
      "Xiu Hui",
      "Li Yan",
      "Yan Wen",
      "Jing Xiu",
      "Hui Fang",
      "Qing Xuan",
      "Yu Ling",
      "Fang Xin",
      "Xin Li",
      "Mei Wei",
      "Xiu Xin",
      "Li Jie",
      "Yan Yu",
      "Jing Yan",
      "Hui Chen",
      "Qing Jia",
      "Yu Jing",
      "Fang Yu",
      "Xin Hui",
      "Mei Yu"
    ];
  }
}
