import '../zone.dart';

/// Zone Egypt
class Egypt extends Zone {
  @override
  String id = "egypt";
  Egypt() {
    surnames = [
      // List of surnames
      "Abdel-Meguid",
      "Ahmed",
      "Ali",
      "Amin",
      "Aziz",
      "Badawi",
      "El-Adl",
      "El-Amir",
      "El-Azab",
      "El-Bakry",
      "El-Din",
      "El-Farouk",
      "El-Gabry",
      "El-Hakim",
      "El-Kassas",
      "El-Masry",
      "El-Naggar",
      "El-Sayed",
      "El-Sherif",
      "El-Tayeb",
      "El-Zoghby",
      "Fahmy",
      "Fawzy",
      "Gaber",
      "Gad",
      "Ghanem",
      "Habib",
      "Hakim",
      "Hassan",
      "Hussein",
      "Ibrahim",
      "Kamel",
      "Khalil",
      "Mahmoud",
      "Mansour",
      "Mikhail",
      "Mohamed",
      "Mokhtar",
      "Morsi",
      "Moussa",
      "Naguib",
      "Nasr",
      "Osman",
      "Ragab",
      "Rashid",
      "Rizk",
      "Saeed",
      "Salem",
      "Salib",
      "Sarraf",
      "Selim",
      "Shaaban",
      "Shafik",
      "Shehata",
      "Shukri",
      "Soliman",
      "Tadros",
      "Tawfik",
      "Youssef",
      "Zaki",
      "Zakaria",
      "Zaki",
      "Zayed",
      "Zaki",
      "Ziad",
      "Zikry",
      "Zuhdi"
    ];

    namesM = [
      // List of male names
      "Amir",
      "Hassan",
      "Ahmed",
      "Mahmoud",
      "Khaled",
      "Youssef",
      "Ali",
      "Tarek",
      "Omar",
      "Ibrahim",
      "Adel",
      "Karim",
      "Mohamed",
      "Sami",
      "Nasser",
      "Rami",
      "Hesham",
      "Fahd",
      "Wael",
      "Emad",
      "Yasin",
      "Rashid",
      "Hany",
      "Amr",
      "Hani",
      "Hussein",
      "Ayman",
      "Kamal",
      "Mustafa",
      "Zakaria",
      "Ehab",
      "Osama",
      "Mamdouh",
      "Salah",
      "Bassem",
      "Raafat",
      "Sherif",
      "Abdullah",
      "Yahya",
      "Mazen",
      "Hatem",
      "Maged",
      "Saad",
      "Hamdy",
      "Nabil",
      "Khaled",
      "Mohsen",
      "Ziad",
      "Ashraf",
      "Waleed",
      "Tamer",
      "Nagi",
      "Naguib",
      "Shadi",
      "Wagih",
      "Toufic",
      "Makram",
      "Shawky",
      "Fathi",
      "Farid",
      "Medhat",
      "Samir",
      "Kassem",
      "Gamal",
      "Sameh",
      "Ismail",
      "Khalid",
      "Ihab",
      "Anwar",
      "Wassim",
      "Saeed",
      "Walid",
      "Gaber",
      "Taha",
      "Diaa",
      "Karim",
      "Tawfiq",
      "Mokhtar",
      "Tawfik",
      "Karam",
      "Sherif",
      "Ragab",
      "Reda",
      "Nageh",
      "Fouad",
      "Magdy",
      "Tareq",
      "Naji",
      "Nader",
      "Hesham",
      "Mamdouh",
      "Khaled",
      "Atef",
      "Hamid",
      "Zaki",
      "Rafik",
      "Khalil"
    ];

    namesW = [
      // List of female names
      "Amira", "Nour", "Layla", "Amina", "Safia", "Yasmin", "Fatima", "Hana",
      "Leila", "Zahra", "Aya", "Maha", "Rania", "Mona", "Sara", "Dina", "Hoda",
      "Asma", "Samar",
      "Salma",
      "Farida", "Ines", "Riham", "Dalal", "Sahar", "Mai", "Zainab", "Mariam",
      "Reem", "Nada",
      "Maya", "Zeinab", "Faten", "Shadia", "Rasha", "Fadia", "Lina", "Heba",
      "Yasmine", "Nagla",
      "Jihan", "Soma", "Shaimaa", "Nadia", "Hanan", "Amal", "Hagar", "Riham",
      "Nermine", "Wafaa",
      "Ola", "Hayam", "Noha", "Warda", "Rawya", "Reham", "Afaf", "Saida",
      "Dalia", "Nihal",
      "Eman", "Nermin", "Ebtissam", "Magda", "Ibtisam", "Hind", "Mervat",
      "Hanan", "Fayza", "Nihal",
      "Intisar", "Shahira", "Samia", "Abeer", "Soraya", "Sawsan", "Sahar",
      "Amira", "Noha", "Hoda",
      "Amina", "Salwa", "Laila", "Rabab", "Ghada", "Samira", "Shadia", "Nabila",
      "Hala", "Sabah",
      "Rania", "Warda", "Dalida", "Iman", "Safa"
    ];
  }
}
