import '../zone.dart';

/// Zone Finland
class Finland extends Zone {
  @override
  String id = "finland";
  Finland() {
    surnames = [
      // List of surnames
      "Virtanen",
      "Mäkinen",
      "Nieminen",
      "Korhonen",
      "Mäkelä",
      "Hämäläinen",
      "Laine",
      "Heikkinen",
      "Koskinen",
      "Järvinen",
      "Lehtonen",
      "Jokinen",
      "Takala",
      "Lahtinen",
      "Leppänen",
      "Aalto",
      "Rantanen",
      "Kinnunen",
      "Salonen",
      "Turunen",
      "Savolainen",
      "Ojala",
      "Koivisto",
      "Ranta",
      "Laaksonen",
      "Rinne",
      "Salo",
      "Laitinen",
      "Karjalainen",
      "Kallio",
      "Mattila",
      "Sipilä",
      "Rautiainen",
      "Leinonen",
      "Rantala",
      "Lahti",
      "Hakala",
      "Miettinen",
      "Peltola",
      "Anttila",
      "Koivunen",
      "Laitinen",
      "Harju",
      "Kujala",
      "Järvelä",
      "Pitkänen",
      "Vainio",
      "Auvinen",
      "Nurmi",
      "Hakkarainen",
      "Väisänen",
      "Lindholm",
      "Tiainen",
      "Salmi",
      "Hietala",
      "Paavola",
      "Savola",
      "Manninen",
      "Ahonen",
      "Holopainen",
      "Korpela",
      "Hartikainen",
      "Niskanen",
      "Hyvärinen",
      "Lappalainen",
      "Heikkilä",
      "Ahola",
      "Toivonen",
      "Hietanen",
      "Vainionpää",
      "Holm",
      "Lampinen",
      "Kärkkäinen",
      "Hannula",
      "Viitanen",
      "Harju",
      "Jutila",
      "Tolonen",
      "Korpi",
      "Miettinen",
      "Lehto",
      "Tuomi",
      "Pulkkinen",
      "Ahokas",
      "Rautio",
      "Kautto",
      "Huhtala",
      "Kujanpää",
      "Pietarinen",
      "Kokko",
      "Virta",
      "Repo",
      "Valtonen",
      "Pesonen",
      "Mäenpää",
      "Tervonen"
    ];

    namesM = [
      // List of male names
      "Elias", "Mikael", "Matias", "Aleksi", "Anton", "Oliver", "Eetu", "Eino",
      "Oskari", "Joona",
      "Akseli", "Matti", "Sami", "Joonas", "Lauri", "Tomi", "Eemeli", "Aapo",
      "Veeti", "Saku",
      "Topi", "Henrik", "Kalle", "Valtteri", "Joakim", "Viljami", "Paavo",
      "Arttu", "Väinö", "Eemil",
      "Ilkka", "Niko", "Rasmus", "Teemu", "Jari", "Vilho", "Olli", "Tuomas",
      "Mika", "Jaakko",
      "Aaro", "Eelis", "Lasse", "Tapio", "Eero", "Panu", "Kristian", "Atte",
      "Otto", "Timo",
      "Juhani", "Simo", "Kimmo", "Miro", "Jere", "Kai", "Pekka", "Ari", "Toni",
      "Erik",
      "Antti", "Jarno", "Samuli", "Oiva", "Jussi", "Pertti", "Tero", "Riku",
      "Kari", "Esa",
      "Sauli", "Asko", "Heikki", "Osmo", "Jani", "Reijo", "Veli", "Aulis",
      "Seppo", "Erkki",
      "Harri", "Tapio", "Timo", "Matti", "Petri", "Pekka", "Juhani", "Antti",
      "Markku", "Ilkka",
      "Juha"
    ];

    namesW = [
      // List of female names
      "Emma",
      "Aino",
      "Sofia",
      "Helmi",
      "Aada",
      "Lilja",
      "Iida",
      "Olivia",
      "Ella",
      "Venla",
      "Aurora",
      "Siiri",
      "Elsa",
      "Vilma",
      "Alma",
      "Anni",
      "Ellen",
      "Mila",
      "Aamu",
      "Aina",
      "Aira",
      "Anniina",
      "Auli",
      "Eerika",
      "Eevi",
      "Eeva",
      "Emmi",
      "Hanna",
      "Hannele",
      "Heidi",
      "Heli",
      "Iina",
      "Inka",
      "Janika",
      "Jasmin",
      "Jenna",
      "Julia",
      "Kaarina",
      "Kaisa",
      "Katriina",
      "Katja",
      "Kiira",
      "Laura",
      "Leena",
      "Liisa",
      "Maija",
      "Mari",
      "Marika",
      "Marja",
      "Milla",
      "Mira",
      "Nelli",
      "Noora",
      "Oona",
      "Paula",
      "Pihla",
      "Päivi",
      "Riikka",
      "Ritva",
      "Roosa",
      "Sari",
      "Satu",
      "Sirkka",
      "Sofie",
      "Sohvi",
      "Susanna",
      "Taika",
      "Tarja",
      "Tiia",
      "Tiina",
      "Tuuli",
      "Ulla",
      "Unna",
      "Ursula",
      "Varpu",
      "Veera",
      "Viivi",
      "Vilja",
      "Vilhelmiina",
      "Virpi",
      "Ylva",
      "Yrjölä",
      "Äini",
      "Örölä"
    ];
  }
}
