import '../zone.dart';

class India extends Zone {
  India() {
    surnames = [
      // List of surnames
      "Patel", "Sharma", "Gupta", "Singh", "Kumar", "Jain", "Verma", "Reddy",
      "Yadav", "Pandey",
      "Mishra", "Choudhary", "Rao", "Rajput", "Thakur", "Sinha", "Mahto",
      "Mehta", "Chauhan", "Malhotra",
      "Bhatia", "Agarwal", "Saxena", "Yadav", "Chopra", "Soni", "Mehra",
      "Srivastava", "Puri", "Varma",
      "Dubey", "Shukla", "Shah", "Dutta", "Biswas", "Das", "Chatterjee", "Nair",
      "Menon", "Iyer",
      "Pillai", "Sood", "Rastogi", "Bhattacharya", "Balakrishnan", "Kulkarni",
      "Desai", "Jha", "Patil", "Banerjee",
      "Kapoor", "Mukherjee", "Agrawal", "Goswami", "Dixit", "Sengupta",
      "Khanna", "Bhat", "Raman", "Mittal",
      "Gandhi", "Bajaj", "Tiwari", "Lal", "Nath", "Roy", "Seth", "Chandra",
      "Verma", "Ray",
      "Rai", "Mahajan", "Choudhury", "Ramachandran", "Rajan", "Malik",
      "Venkatesh", "Iyengar", "Krishnan", "Menon",
      "Prasad", "Nanda", "Rangan", "Kannan", "Chopra", "Kadam", "Deshpande",
      "More", "Soman", "Shetty",
      "Naik", "Fernandes", "Fadnavis", "Shroff", "Shanmugam", "Bhandari",
      "Tandon", "Dubey", "Bhalla", "Sikka"
    ];

    namesM = [
      // List of male names
      "Ravi", "Amit", "Vikram", "Rahul", "Suresh", "Anil", "Gaurav", "Prakash",
      "Rajesh", "Arun",
      "Vijay", "Kamal", "Sanjay", "Rajiv", "Naveen", "Manish", "Alok",
      "Sandeep", "Dinesh", "Vinod",
      "Ramesh", "Sunil", "Ajay", "Mukesh", "Rajendra", "Deepak", "Vivek",
      "Pankaj", "Pawan", "Harish",
      "Rajeev", "Nitin", "Amar", "Rohan", "Sudhir", "Hemant", "Nikhil",
      "Aashish", "Aryan", "Rahim",
      "Vishal", "Mayank", "Ashok", "Aditya", "Raju", "Yash", "Sushant", "Kunal",
      "Abhishek", "Shankar",
      "Shyam", "Krishna", "Jitendra", "Ganesh", "Sachin", "Rajat", "Shubham",
      "Amitabh", "Rajnikant",
      "Ajay", "Pradeep", "Jai", "Vikas", "Narayan", "Arun", "Rajkumar",
      "Rakesh", "Nikhil", "Navin",
      "Rajnish", "Rajiv", "Alokesh", "Avinash", "Rajeshwar", "Anand", "Harsh",
      "Surya", "Dheeraj", "Aadesh",
      "Vijayendra", "Praveen", "Rajendra", "Raghav", "Anupam", "Ajit", "Satish",
      "Amitava", "Arunabh",
      "Rohit", "Parth", "Prem", "Rishi", "Karthik", "Samarth", "Utkarsh",
      "Varun", "Vishnu", "Zubin"
    ];

    namesW = [
      // List of female names
      "Ananya",
      "Priya",
      "Aishwarya",
      "Neha",
      "Riya",
      "Sneha",
      "Swati",
      "Shreya",
      "Divya",
      "Kavita",
      "Pooja",
      "Rashmi",
      "Sakshi",
      "Simran",
      "Aarti",
      "Jyoti",
      "Nidhi",
      "Asha",
      "Poonam",
      "Ritu",
      "Sunita",
      "Tanvi",
      "Meera",
      "Anita",
      "Geeta",
      "Kiran",
      "Rani",
      "Rekha",
      "Namita",
      "Nisha",
      "Mamta",
      "Monika",
      "Sarita",
      "Sheetal",
      "Sita",
      "Uma",
      "Vandana",
      "Zara",
      "Fatima",
      "Parveen",
      "Ayesha",
      "Zoya",
      "Khushi",
      "Amrita",
      "Harpreet",
      "Rupal",
      "Shabnam",
      "Yamini",
      "Farida",
      "Indira",
      "Chitra",
      "Aarti",
      "Kalyani",
      "Leela",
      "Madhuri",
      "Nalini",
      "Ojaswini",
      "Prerna",
      "Rakhi",
      "Sadhana",
      "Taruni",
      "Urmila",
      "Vani",
      "Wamika",
      "Xara",
      "Yamuna",
      "Zaina",
      "Aditi",
      "Bhavya",
      "Charulata",
      "Deeksha",
      "Esha",
      "Falguni",
      "Gauri",
      "Hema",
      "Ishita",
      "Jaya",
      "Kajal",
      "Lakshmi",
      "Malini",
      "Nandita",
      "Oorvi",
      "Pallavi",
      "Radha",
      "Sita",
      "Trisha",
      "Urmila",
      "Varsha",
      "Winnie",
      "Xena",
      "Yashica",
      "Zaina"
    ];
  }
}
