import '../zone.dart';

class Spain extends Zone {
  bool _twoSurnames = false;
  Spain({bool twoSurnames = false}) {
    _twoSurnames = twoSurnames;
    surnames = [
      "García",
      "Rodríguez",
      "González",
      "Fernández",
      "López",
      "Martínez",
      "Sánchez",
      "Pérez",
      "Gómez",
      "Martín",
      "Jiménez",
      "Ruiz",
      "Hernández",
      "Díaz",
      "Moreno",
      "Muñoz",
      "Álvarez",
      "Romero",
      "Alonso",
      "Gutiérrez",
      "Navarro",
      "Torres",
      "Domínguez",
      "Vázquez",
      "Ramos",
      "Gil",
      "Ramírez",
      "Serrano",
      "Blanco",
      "Molina",
      "Morales",
      "Suárez",
      "Ortega",
      "Delgado",
      "Castro",
      "Ortiz",
      "Rubio",
      "Marín",
      "Sanz",
      "Núñez",
      "Iglesias",
      "Medina",
      "Cortés",
      "Garrido",
      "Castillo",
      "Santos",
      "Lozano",
      "Guerrero",
      "Cano",
      "Prieto",
      "Méndez",
      "Cruz",
      "Calvo",
      "Herrera",
      "Gallego",
      "Flores",
      "Márquez",
      "León",
      "Peña",
      "Vidal",
      "Cabrera",
      "Campos",
      "Vega",
      "Fuentes",
      "Carrasco",
      "Díez",
      "Reyes",
      "Caballero",
      "Nieto",
      "Aguilar",
      "Santana",
      "Pascual",
      "Herrero",
      "Montero",
      "Hidalgo",
      "Lorenzo",
      "Giménez",
      "Ibáñez",
      "Ferrer",
      "Santiago",
      "Durán",
      "Vargas",
      "Benítez",
      "Mora",
      "Arias",
      "Vicente",
      "Carmona",
      "Crespo",
      "Román",
      "Soto",
      "Pastor",
      "Sáez",
      "Velasco",
      "Moya",
      "Soler",
      "Parra",
      "Rojas",
      "Esteban",
      "Bravo",
      "Gallardo",
      "Carreras"
    ];

    namesM = [
      "Antonio",
      "José",
      "Manuel",
      "Francisco",
      "David",
      "Juan",
      "José Antonio",
      "Javier",
      "Daniel",
      "José Luis",
      "Francisco Javier",
      "Carlos",
      "Jesús",
      "Alejandro",
      "Miguel",
      "José Manuel",
      "Rafael",
      "Miguel Angel",
      "Pedro",
      "Ángel",
      "Pablo",
      "José María",
      "Sergio",
      "Fernando",
      "Luis",
      "Jorge",
      "Alberto",
      "Juan Carlos",
      "Álvaro",
      "Juan José",
      "Adrián",
      "Diego",
      "Raúl",
      "Juan Antonio",
      "Iván",
      "Enrique",
      "Rubén",
      "Ramón",
      "Óscar",
      "Vicente",
      "Andrés",
      "Juan Manuel",
      "Joaquín",
      "Santiago",
      "Eduardo",
      "Víctor",
      "Mario",
      "Roberto",
      "Jaime",
      "Francisco José",
      "Marcos",
      "Ignacio",
      "Alfonso",
      "Jordi",
      "Ricardo",
      "Salvador",
      "Hugo",
      "Emilio",
      "Guillermo",
      "Gabriel",
      "Marc",
      "Julio",
      "Julián",
      "Gonzalo",
      "José Miguel",
      "Tomás",
      "Mohamed",
      "Agustín",
      "Martín",
      "José Ramón",
      "Nicolás",
      "Félix",
      "Joan",
      "Ismael",
      "Cristian",
      "Samuel",
      "Aitor",
      "Héctor",
      "Juan Francisco",
      "Josep",
      "Maríano",
      "Lucas",
      "José Carlos",
      "Iker",
      "Domingo",
      "Sebastián",
      "Alfredo",
      "Álex",
      "César",
      "Felipe",
      "José Ángel",
      "José Ignacio",
      "Víctor Manuel",
      "Rodrigo",
      "Luis Miguel",
      "José Francisco",
      "Juan Luis",
      "Gregorio",
      "Xavier",
      "Albert"
    ];

    namesW = [
      "María Carmen",
      "María",
      "Carmen",
      "Josefa",
      "Ana María",
      "Isabel",
      "María Pilar",
      "María Dolores",
      "Laura",
      "María Teresa",
      "Ana",
      "Cristina",
      "María Ángeles",
      "Marta",
      "Francisca",
      "Antonia",
      "María Isabel",
      "María José",
      "Lucía",
      "Dolores",
      "Sara",
      "Paula",
      "Elena",
      "María Luisa",
      "Pilar",
      "Raquel",
      "Rosa María",
      "Concepción",
      "Manuela",
      "Mercedes",
      "María Jesús",
      "Beatriz",
      "Julia",
      "Rosario",
      "Nuria",
      "Juana",
      "Silvia",
      "Teresa",
      "Encarnación",
      "Irene",
      "Alba",
      "Patricia",
      "Montserrat",
      "Andrea",
      "Rocío",
      "Rosa",
      "Mónica",
      "Alicia",
      "María del Mar",
      "Ángela",
      "Sonia",
      "Sandra",
      "Marina",
      "Susana",
      "Natalia",
      "Yolanda",
      "Margarita",
      "María Josefa",
      "Claudia",
      "Eva",
      "María Rosario",
      "Inmaculada",
      "María Mercedes",
      "Ana Isabel",
      "Esther",
      "Carla",
      "Sofia",
      "Noelia",
      "Verónica",
      "Ángeles",
      "Nerea",
      "Carolina",
      "María Victoria",
      "Eva María",
      "María Rosa",
      "Míriam",
      "Inés",
      "Lorena",
      "Amparo",
      "Ana Belén",
      "María Concepción",
      "María Elena",
      "Victoria",
      "Daniela",
      "María Antonia",
      "Catalina",
      "Lidia",
      "Consuelo",
      "María Nieves",
      "Celia",
      "Alejandra",
      "Martina",
      "Olga",
      "Gloria",
      "Emilia",
      "Ainhoa",
      "Luisa",
      "Fátima",
      "María Soledad",
      "Aurora"
    ];
  }

  @override
  String get fullNameStructure => _twoSurnames ? "_N_ _S_ _S_" : "_N_ _S_";
}
